version: "3"
services:
  app:
    image: postgres:14.9
    container_name: TasksDB
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
